### PR TITLE
Added support for latest torch; zmq > 3.0

### PR DESCRIPTION
**Pull request by moof2k**

### CODE REVIEW

**Comment by soumith** [comment]
this is quite sweet! thanks...

**Comment by soumith** [comment]
there seem to be merge conflicts. do you think you need to merge any of these commits in between by andreirusu : https://github.com/clementfarabet/lua---parallel/commits/master

**Comment by moof2k** [comment]
Ah, I wish I had seen those changes earlier. I didn't realize @fidlej 's branch was behind.

OK it's all up to date now.. I nuked my changes to init.lua as they have now been superseded.

You'll probably want to update the README to point to your repo (or publish a new luarock)

**Comment by soumith** [comment]
nice, testing it out now :) thanks again.

**Pull request merged**
